#!/bin/sh
set -e

init_target (){
	echo "Cleaning Target $1"
	rm -r targets/$1 || true
	mkdir -p targets/$1/_jhbuild/manifests
	cp -a targets/gimp-common/_jhbuild/manifests/* targets/$1/_jhbuild/manifests
	cp -a targets/gimp-common/_jhbuild/packagedb.xml targets/$1/_jhbuild/
}

chmod a-w win32.cache

export BUILD_FLAVOUR=rls

export MODULE=gimp-common
jhbuild --file=build.jhbuildrc $*

./targetisunchanged gimp-common gimp-stable || init_target gimp-stable
export MODULE=gimp-stable
jhbuild --file=build.jhbuildrc build --start-at=gimp-common $*

./targetisunchanged gimp-common gimp-dev || init_target gimp-dev
export MODULE=gimp-dev
jhbuild --file=build.jhbuildrc build --start-at=gimp-common $*

chmod u+w win32.cache
