#!/bin/bash

dostuff (){
	f=$1-i686-`date +%Y-%m-%d`

	mkdir -p combined/$f
	cp -R -d --reflink=auto ./gimp-common/* combined/$f
	cp -R -d --reflink=auto ./$1/* combined/$f

	pushd combined
	pushd $f

	rm -r _jhbuild
	rm -r man
	rm -r share/doc
	rm -r share/gtk-doc
	rm -r share/gtk-2.0/demo
	rm -r share/icons
	rm -r share/applications
	rm -r share/info
	rm -r share/man
	rm -r share/gdb
	rm -r share/gettext

	rm etc/gconf/2/path.jhbuild

	rm `find -name *.exe | sed -e /gimp/d -e /gspawn/d`

	pushd bin
	rm `ls | sed -e /.exe/d -e /.dll/d`
	popd

	rm `find -name *.html`
	rm `find -name *.a`
	rm `find -name *.def`
	rm `find -name *.sh`
	rm `find -name *.h`
	rm `find -name *.c`
	rm `find -name *.hxx`
	rm `find -name *.pc`
	rm `find -name *.m4`
	rm `find -name *.manifest`

	find -depth -type d -empty -exec rmdir {} \;

	echo "@echo off
SET PATH=%~dp0bin\\
SET BABL_PATH=%~dp0lib\babl-0.1\\
start $2" | unix2dos > run_gimp.bat

	popd

	if [ -e $f/bin/gimp-2.*.exe ]; then
		7z a -t7z -m0=lzma -mx=9 -mfb=64 -md=32m -ms=on $f.7z $f
		cat ~/bin/7z.sfx $f.7z > $f.exe
		rm $f.7z
	else
		echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
		echo "!!            GIMP EXECUTABLE NOT FOUND                !!"
		echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
	fi

	rm -r $f

	popd
}

cd targets
dostuff gimp-stable gimp-2.8.exe
dostuff gimp-dev gimp-2.9.exe
